# vim ft=yaml
# travis-ci.org definition

sudo: required

language: cpp
compiler:
#  - gcc
  - clang
cache:
  - apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - mariadb-10
    packages:
      - llvm-3.6
      - gcc-4.9
      - g++-4.9
      - binutils
#      - libjemalloc-dev
      - hardening-wrapper
      - zlib1g-dev
      - libbz2-dev
      - libsnappy-dev
      - libtool
      - libncurses5-dev
      - perl
      - libwrap0-dev
      - zlib1g-dev
      - libreadline-gplv2-dev
      - libssl-dev
      - libpam0g-dev
      - psmisc
      - po-debconf
      - chrpath
      - automake1.9
      - doxygen
      - texlive-latex-base
      - ghostscript
      - dpatch
      - gawk
      - bison
      - lsb-release
      - libaio-dev
      - devscripts
      - libevent-dev
before_install:
# - sudo add-apt-repository -y "deb https://downloads.mariadb.com/files/MariaDB/repo/10.0/ubuntu precise main"
 - sudo add-apt-repository -y 'deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu precise main'
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x1BB943DB
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq  libjemalloc-dev
# need to do before installing hardening-wrapper
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
# still whitelist applies in VM mode
 - sudo apt-get install -y -qq  hardening-wrapper libreadline-gplv2-dev automake1.9 dpatch libaio-dev
# devscripts equivs
#  - sudo mk-build-deps --install debian/control
script:
 - export AM_EXTRA_MAKEFLAGS=VERBOSE=1
 - export PATH=/usr/local/clang-3.6/bin/:${PATH}
 - export MYSQL_BUILD_CC=`which ${CC}`
 - export MYSQL_BUILD_CXX=`which ${CXX}`
 - which clang
 - which clang++
 - DEB_BUILD_OPTIONS="parallel=4" debian/autobake-deb.sh && cd mysql-test && ./mtr
notifications:
  irc:
    channels:
      - "chat.freenode.net#maria"
    on_success: never # [always|never|change]
    on_failure: never
