# vim ft=yaml
# travis-ci.org definition

language: cpp
compiler: gcc
#  - clang
cache:
  - apt
before_install:
  # As of this writing (10 May 2014) the Travis build environment is Ubuntu 12.04,
  # which needs the following ugly dependency incantations to build RocksDB:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gcc-4.9 g++-4.9 zlib1g-dev libbz2-dev libsnappy-dev libjemalloc-dev libtool libncurses5-dev perl libwrap0-dev zlib1g-dev  libreadline-gplv2-dev libssl-dev libpam0g-dev psmisc po-debconf chrpath automake1.9 doxygen texlive-latex-base ghostscript dpatch gawk bison lsb-release hardening-wrapper libaio-dev devscripts
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
# devscripts equivs
#  - sudo mk-build-deps --install debian/control
script: env DEB_BUILD_OPTIONS="parallel=4" debian/autobake-deb.sh && cd mysql-test && ./mtr
notifications:
  irc:
    channels:
      - "chat.freenode.net#maria"
    on_success: never # [always|never|change]
    on_failure: never
