# vim ft=yaml
# travis-ci.org definition
language: cpp
compiler:
  - gcc
  - clang
cache:
  - ccache
  - apt
before_install:
# https://mariadb.com/kb/en/mariadb/building-mariadb-release-on-ubuntu-1204-lts-precise-pangolin/
  - sudo apt-get update -qq
  - sudo apt-get -t precise-updates -y install libtool libncurses5-dev perl libwrap0-dev zlib1g-dev  libreadline-gplv2-dev libssl-dev libpam0g-dev psmisc po-debconf chrpath automake1.9 doxygen texlive-latex-base ghostscript dpatch gawk bison lsb-release hardening-wrapper libaio-dev devscripts
  - wget https://ftp-master.debian.org/keys/archive-key-7.0.asc -O - | apt-key add -
  - echo deb http://ftp.us.debian.org/debian/ wheezy main > /etc/apt/sources.list.d/wheezy.list
  - sudo apt-get update -qq
  - sudo apt-get -t wheezy -y install gcc cmake binutils libjemalloc-dev
#  - wget http://ftp.at.debian.org/debian/pool/main/j/jemalloc/libjemalloc-dev_3.0.0-3_amd64.deb  http://http.us.debian.org/debian/pool/main/j/jemalloc/libjemalloc1_3.0.0-3_amd64.deb
#  - sudo dpkg -i libjemalloc1_3.0.0-3_amd64.deb libjemalloc-dev_3.0.0-3_amd64.deb
# devscripts equivs
#  - sudo mk-build-deps --install debian/control
install:
  - echo | env DEB_BUILD_OPTIONS="parallel=4" debian/autobake-deb.sh
#  - cmake . -DBUILD_CONFIG=mysql_release -DWITH_SSL=yes && make
#  - cmake -DCMAKE_BUILD_TYPE=Debug  . && make -j4
script:
  - cd mysql-test
  - ./mtr
notifications:
  irc: "chat.freenode.net#maria"
  on_success: never # [always|never|change]
  on_failure: never
